### ISSUE TITLE
Show response from django in a modal

### ISSUE THREAD

**Issue by GraceCeline** [GraceCeline/Angular#3]
https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by vktrrdk** [comment]
We want to handle the response we get from django and show it in a modal.
The Bootstrap Modals (please add Bootstrap to your angular application so you can easily style your templates!) can be used to show this information. As always, check the webapps of the de.NBI repositories to see how we solved things like this!

**Comment by GraceCeline** [comment]
show response codes in the modal. also show modal when a workshop is succesfully created
